### ISSUE TITLE
segment subdomains 

### ISSUE THREAD

**Issue by atomGit** [saihon/navigate-location#1]
please consider segmenting subdomains so that we can go from sub.domain.com to domain.com

**Comment by saihon** [comment]
Sorry, I don't it.
Reason is that it is difficult to simply split a domain, so I have to use a public suffix list.

**Comment by atomGit** [comment]
would like to revisit this...

i don't understand why it would be difficult to split a subdomain since the splitter is always a dot

```
www.sub.domain.tld/
sub.domain.tld/
domain.tld/

sub.domain.co.uk/
domain.co.uk/
co.uk/ (won't work, but this isn't really an issue - it can be up to the user to not click this entry)
```

so in other words, just split at every dot up to the domain and tld before the first slash

**Comment by saihon** [comment]
Hi @atomGit, thank you comment.

`www.sub.domain.tld/` should be split into `ww.sub.` and `domain.tld/`,  Similarly, `sub.domain.co.uk/` should be split into `sub.` and `domain.co.uk/`. Also `domain.co.uk` does not split.
I think to split these domains correctly in two, I need to know the position of “.domain.”. To do that, I need the suffix list.
Have you any other way to split the correctly?

**Comment by atomGit** [comment]
> Also domain.co.uk does not split.

right, but i think it's acceptable to split it anyway to keep things simple - the user will know that co.uk isn't a valid address - it's either that, or incorporating a suffix list as you said and i think that is probably unnecessary

**Comment by saihon** [comment]
Personally, I don't agree with having invalid links.
However, not many people use this addon, so if you send a pull-request, I will merge it.

**Comment by atomGit** [comment]
sorry, i don't code JS

i respect your decision - if you wanted to have a look at another add-on anyway and see how they're doing it, you might look at [Navigate UP](https://addons.mozilla.org/en-US/firefox/addon/navigate-up-we/) background.js starting around line 340

**Comment by saihon** [comment]
I looked at the source code for the add-on you showed.
There is a file there called publicsuffixlist.js to work around invalid URLs.
Sorry, but I don't want to implement code that I don't agree with myself.

**Comment by atomGit** [comment]
i understand - not a problem
